import abc
from . import Sieve
from typing import Any

def ensure_comparison(value: Any): ...

class CacheMixin(Sieve, metaclass=abc.ABCMeta):
    def latest_builds(self, session: Any, tag_id: Any, inherit: bool = ...): ...
    def latest_build_ids(self, session: Any, tag_id: Any, inherit: bool = ...): ...
    def latest_builds_by_name(self, session: Any, tag_id: Any, inherit: bool = ...): ...
    def latest_maven_builds(self, session: Any, tag_id: Any, inherit: bool = ...): ...
    def latest_maven_build_ids(self, session: Any, tag_id: Any, inherit: bool = ...): ...
    def bulk_list_packages(self, session: Any, tag_ids: Any, inherited: bool = ...): ...
    def list_packages(self, session: Any, tag_id: Any, inherited: bool = ...): ...
    def allowed_packages(self, session: Any, tag_id: Any, inherited: bool = ...): ...
    def blocked_packages(self, session: Any, tag_id: Any, inherited: bool = ...): ...
    def get_tag_groups(self, session: Any, tag_id: Any): ...
    def bulk_get_tag_groups(self, session: Any, tag_ids: Any): ...
