from koji import ClientSession
from typing import Any, Optional

class ManagedClientSession(ClientSession):
    def __enter__(self): ...
    rsession: Any = ...
    def __exit__(self, exc_type: Any, _exc_val: Any, _exc_tb: Any): ...

class ProfileClientSession(ManagedClientSession):
    def __init__(self, profile: str = ...) -> None: ...

class AnonClientSession(ProfileClientSession):
    def __enter__(self): ...

class BadDingo(Exception):
    complaint: str = ...

class NoSuchBuild(BadDingo):
    complaint: str = ...

class NoSuchHost(BadDingo):
    complaint: str = ...

class NoSuchChannel(BadDingo):
    complaint: str = ...

class NoSuchContentGenerator(BadDingo):
    complaint: str = ...

class NoSuchTag(BadDingo):
    complaint: str = ...

class NoSuchTarget(BadDingo):
    complaint: str = ...

class NoSuchTask(BadDingo):
    complaint: str = ...

class NoSuchUser(BadDingo):
    complaint: str = ...

class NoSuchPermission(BadDingo):
    complaint: str = ...

class NoSuchArchive(BadDingo):
    complaint: str = ...

class NoSuchRPM(BadDingo):
    complaint: str = ...

class NotPermitted(BadDingo):
    complaint: str = ...

class FeatureUnavailable(BadDingo):
    complaint: str = ...

def iter_bulk_load(session: Any, loadfn: Any, keys: Any, err: bool = ..., size: int = ...) -> None: ...
def bulk_load(session: Any, loadfn: Any, keys: Any, err: bool = ..., size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_builds(session: Any, nvrs: Any, err: bool = ..., size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_tasks(session: Any, task_ids: Any, request: bool = ..., err: bool = ..., size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_tags(session: Any, tags: Any, err: bool = ..., size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_rpm_sigs(session: Any, rpm_ids: Any, size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_buildroot_archives(session: Any, buildroot_ids: Any, btype: Optional[Any] = ..., size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_buildroot_rpms(session: Any, buildroot_ids: Any, size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_build_archives(session: Any, build_ids: Any, btype: Optional[Any] = ..., size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_build_rpms(session: Any, build_ids: Any, size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_buildroots(session: Any, broot_ids: Any, size: int = ..., results: Optional[Any] = ...): ...
def bulk_load_users(session: Any, users: Any, err: bool = ..., size: int = ..., results: Optional[Any] = ...): ...
def as_buildinfo(session: Any, build: Any): ...
def as_taginfo(session: Any, tag: Any): ...
def as_taskinfo(session: Any, task: Any): ...
def as_targetinfo(session: Any, target: Any): ...
def as_hostinfo(session: Any, host: Any): ...
def as_archiveinfo(session: Any, archive: Any): ...
def as_rpminfo(session: Any, rpm: Any): ...
def as_userinfo(session: Any, user: Any): ...
def hub_version(session: Any): ...
def version_check(session: Any, minimum: Any = ...): ...
def version_require(session: Any, minimum: Any = ..., message: Optional[Any] = ...): ...
