from typing import Any, Optional

def chunkseq(seq: Any, chunksize: Any): ...
def fnmatches(value: Any, patterns: Any, ignore_case: bool = ...): ...
def update_extend(dict_orig: Any, *dict_additions: Any): ...
def merge_extend(*dict_additions: Any): ...
def globfilter(seq: Any, patterns: Any, key: Optional[Any] = ..., invert: bool = ..., ignore_case: bool = ...): ...
def rpm_evr_compare(left_evr: Any, right_evr: Any): ...
def unique(sequence: Any, key: Optional[Any] = ...): ...
def parse_datetime(src: Any, strict: bool = ...): ...
def find_config_dirs(): ...
def find_config_files(dirs: Optional[Any] = ...): ...
def load_full_config(config_files: Optional[Any] = ...): ...
def get_plugin_config(conf: Any, plugin: Any, profile: Optional[Any] = ...): ...
def load_plugin_config(plugin: Any, profile: Optional[Any] = ...): ...
