from typing import Any, Optional

def tag_dedup(tag_infos: Any): ...
def ensure_tag(session: Any, name: Any): ...
def resolve_tag(session: Any, name: Any, target: bool = ...): ...
def gather_affected_targets(session: Any, tagnames: Any): ...
def renum_inheritance(inheritance: Any, begin: int = ..., step: int = ...): ...
def find_inheritance_parent(inheritance: Any, parent_id: Any): ...
def convert_tag_extras(taginfo: Any, into: Optional[Any] = ..., prefix: Optional[Any] = ...): ...
def collect_tag_extras(session: Any, taginfo: Any, prefix: Optional[Any] = ...): ...
def gather_tag_ids(session: Any, shallow: Any = ..., deep: Any = ..., results: Optional[Any] = ...): ...
