from typing import Any, Optional

USER_NORMAL: Any
USER_HOST: Any
USER_GROUP: Any
STATUS_NORMAL: Any
STATUS_BLOCKED: Any

def collect_userinfo(session: Any, user: Any): ...
def collect_cg_access(session: Any, user: Any): ...
def collect_cgs(session: Any, name: Optional[Any] = ...): ...
def collect_perminfo(session: Any, permission: Any): ...
