
FROM fedora:28

RUN mkdir -p /src

RUN \
    dnf install -qy \
        dnf-plugins-core make rpm-build which \
        python3-mock python3-nose

COPY Makefile setup.py kojismokydingo-*.tar.gz /src/

RUN \
    cd /src && make srpm && \
    dnf builddep -qy /root/rpmbuild/SRPMS/kojismokydingo-*.src.rpm && \
    rpmbuild --rebuild /root/rpmbuild/SRPMS/kojismokydingo-*.src.rpm && \
    dnf install -qy /root/rpmbuild/RPMS/noarch/*kojismokydingo*.rpm && \
    cd / && rm -rf /src

# The end.
