
FROM centos:8

RUN \
    dnf install -y findutils git make rpm-build dnf-plugins-core epel-release && \
    dnf install -y python3-pip && \
    pip3 install -q nose && \
    ln -s /usr/bin/python3 /usr/bin/python

RUN mkdir -p /src
COPY Makefile setup.py kojismokydingo-*.tar.gz /src

RUN \
    cd /src && make srpm && \
    dnf builddep -y /root/rpmbuild/SRPMS/kojismokydingo-*.src.rpm && \
    rpmbuild --rebuild /root/rpmbuild/SRPMS/kojismokydingo-*.src.rpm && \
    dnf install -y /root/rpmbuild/RPMS/noarch/*kojismokydingo*.rpm && \
    cd / && rm -rf /src


# The end.
