
FROM centos:6

RUN mkdir -p /src

RUN \
    yum install -q -y epel-release && \
    yum install -q -y \
        make rpm-build which yum-utils \
        python-pip python2-mock && \
    python -W "ignore:a true SSLContext" -m pip.__main__ install -q nose

COPY Makefile setup.py kojismokydingo-*.tar.gz /src/

RUN \
    cd /src && make srpm && \
    yum-builddep -q -y /root/rpmbuild/SRPMS/kojismokydingo-*.src.rpm && \
    rpmbuild --rebuild /root/rpmbuild/SRPMS/kojismokydingo-*.src.rpm && \
    yum install -q -y /root/rpmbuild/RPMS/noarch/*kojismokydingo*.rpm && \
    cd / && rm -rf /src

# The end.
