from . import AnonLonelyDingo
from ..cli.builds import FilterBuilds
from typing import Any, Optional

class LonelyFilterBuilds(AnonLonelyDingo, FilterBuilds):
    default_profile: str = ...
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def arguments(self, parser: Any): ...
    def sifter_arguments(self, parser: Any): ...
    def validate(self, parser: Any, options: Any): ...

ksd_filter_builds: Any
