from . import AnonLonelyDingo
from ..cli.tags import FilterTags
from typing import Any, Optional

class LonelyFilterTags(AnonLonelyDingo, FilterTags):
    default_profile: str = ...
    def __init__(self, name: Optional[Any] = ...) -> None: ...
    def arguments(self, parser: Any): ...
    def sifter_arguments(self, parser: Any): ...
    def validate(self, parser: Any, options: Any): ...

ksd_filter_tags: Any
