from . import AnonSmokyDingo
from typing import Any, Optional

def cli_list_build_archives(session: Any, nvrs: Any, btype: Any, atypes: Any = ..., arches: Any = ..., rpmkeys: Any = ..., deleted: bool = ..., path: Optional[Any] = ..., json: bool = ...) -> None: ...
def cli_latest_tag_archives(session: Any, tagname: Any, btype: Any, atypes: Any = ..., arches: Any = ..., rpmkeys: Any = ..., inherit: bool = ..., path: Optional[Any] = ..., json: bool = ...) -> None: ...

class ArchiveFiltering:
    def archive_arguments(self, parser: Any): ...
    def validate_archive_options(self, parser: Any, options: Any) -> None: ...

class ListBuildArchives(AnonSmokyDingo, ArchiveFiltering):
    description: str = ...
    def arguments(self, parser: Any): ...
    def validate(self, parser: Any, options: Any): ...
    def handle(self, options: Any): ...

class LatestArchives(AnonSmokyDingo, ArchiveFiltering):
    description: str = ...
    def arguments(self, parser: Any): ...
    def validate(self, parser: Any, options: Any): ...
    def handle(self, options: Any): ...
