from . import AnonSmokyDingo
from typing import Any, Optional

def cli_client_config(session: Any, goptions: Any, only: Any = ..., quiet: bool = ..., config: bool = ..., json: bool = ...) -> None: ...

class ClientConfig(AnonSmokyDingo):
    group: str = ...
    description: str = ...
    def arguments(self, parser: Any): ...
    def activate(self) -> None: ...
    def handle(self, options: Any): ...

def get_open_command(profile: Optional[Any] = ..., err: bool = ...): ...
def cli_open(session: Any, goptions: Any, datatype: Any, element: Any, command: Optional[Any] = ...) -> None: ...

class ClientOpen(AnonSmokyDingo):
    group: str = ...
    description: str = ...
    def arguments(self, parser: Any): ...
    def validate(self, parser: Any, options: Any) -> None: ...
    def handle(self, options: Any): ...
