from . import AnonSmokyDingo
from typing import Any, Optional

def cli_check_hosts(session: Any, timeout: int = ..., arches: Any = ..., channel: Optional[Any] = ..., ignore: Any = ..., quiet: bool = ..., shush: bool = ...): ...

class CheckHosts(AnonSmokyDingo):
    description: str = ...
    def arguments(self, parser: Any): ...
    def handle(self, options: Any): ...
