from . import AnonSmokyDingo
from typing import Any, Optional

def get_usertype_str(userinfo: Any): ...
def get_userstatus_str(userinfo: Any): ...
def cli_userinfo(session: Any, user: Any, json: bool = ...): ...

class UserInfo(AnonSmokyDingo):
    group: str = ...
    description: str = ...
    def arguments(self, parser: Any): ...
    def handle(self, options: Any): ...

def cli_perminfo(session: Any, permission: Any, verbose: bool = ..., by_date: bool = ..., json: bool = ...) -> None: ...

class PermissionInfo(AnonSmokyDingo):
    description: str = ...
    def arguments(self, parser: Any): ...
    def handle(self, options: Any): ...

def cli_cginfo(session: Any, name: Optional[Any] = ..., json: bool = ...) -> None: ...

class CGInfo(AnonSmokyDingo):
    description: str = ...
    def arguments(self, parser: Any): ...
    def handle(self, options: Any): ...
