
# RHEL 8 pre-beta releases
FROM centos:stream8

WORKDIR /src

RUN \
    dnf upgrade -y && \
    dnf install -qy epel-release && \
    dnf install -qy \
        dnf-plugins-core make rpm-build which \
        python3-docutils python3-nose koji

ARG VERSION

COPY kojismokydingo-${VERSION}.tar.gz tools/*.sh /src/

RUN /src/rpmbuild.sh \
        /src /src/kojismokydingo-${VERSION}.tar.gz

# The end.
