
FROM centos:7

WORKDIR /src

RUN \
    yum install -q -y epel-release && \
    yum install -q -y \
        make rpm-build which yum-utils \
        python2-mock python2-nose

ARG VERSION

COPY kojismokydingo-${VERSION}.tar.gz tools/*.sh /src/

RUN /src/rpmbuild.sh \
        /src /src/kojismokydingo-${VERSION}.tar.gz

# The end.
