
FROM centos:6

WORKDIR /src

RUN \
    yum install -q -y epel-release && \
    yum install -q -y \
        make rpm-build which yum-utils \
        python-docutils python-pip python2-mock koji && \
    python -W "ignore:a true SSLContext" -m pip.__main__ install -q -I \
        nose

ARG VERSION

COPY kojismokydingo-${VERSION}.tar.gz tools/*.sh /src/

RUN /src/rpmbuild.sh \
        /src /src/kojismokydingo-${VERSION}.tar.gz

# The end.
