# Github Action definitions for running a Bandit scan and storing the
# results in the security tab


name: Bandit


on:
  push:
    branches:
      - master
    ignore-paths:
      - 'docs/**'
      - 'examples/**'
      - 'tools/**'
    paths:
      - 'setup.cfg'
      - '**/*.py'
      - '**/*.pyi'
      - '.github/workflows/bandit.yml'

  pull_request:
    ignore-paths:
      - 'docs/**'
      - 'examples/**'
      - 'tools/**'
    paths:
      - 'setup.cfg'
      - '**/*.py'
      - '**/*.pyi'
      - '.github/workflows/bandit.yml'


jobs:
  bandit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install libkrb5-dev
          pip install tox tox-gh-actions

      - name: Run Bandit
        run: tox -e bandit-sarif

      - name: Upload Bandit results
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: Bandit
          sarif_file: bandit.sarif


# The end.
