name: "Build: Wheel"


on:
  workflow_call:
  workflow_dispatch:


jobs:

  build-wheel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip

      - name: Install Dependencies
        run: |
          pip install build

      - name: Generate Wheel
        run: |
          python -B -m build .

      - name: Store Wheel
        uses: actions/upload-artifact@v3
        with:
          name: Wheel
          path: dist/


# The end.
