name: "Build: Documentation"


on:
  workflow_dispatch:
  workflow_call:


jobs:

  build-documentation:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          sudo apt-get install libkrb5-dev make pandoc
          pip install tox tox-gh-actions

      - name: Generate Documentation
        run: |
          make docs

      - name: Store Documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path:
            build/sphinx


# The end.
