name: "Trigger: Nightly"


on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"


jobs:
  test-against-koji-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install libkrb5-dev
          pip install tox tox-gh-actions

      - name: Running tox
        run: |
          tox -e koji-git


# The end.
