# Github Action definition for publishing assets to the release and to
# PyPI when a release is tagged. Also emits a notification post to
# mastodon


name: Release Assets


on:
  release:
    types: [published]


jobs:

  build-wheel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Record package version
        run: |
          mkdir -p dist
          python setup.py --version > dist/VERSION
          cat dist/VERSION >> $GITHUB_STEP_SUMMARY

      - name: Install python dependencies
        run: |
          pip install wheel

      - name: Build Wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Store Wheel
        uses: actions/upload-artifact@v3
        with:
          name: Wheel
          path: dist/

  build-rpms:
    name: Trigger RPM builds
    uses: ./.github/workflows/rpms.yml

  attach-assets:
    name: Attach assets to release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs:
      - build-wheel
      - build-rpms

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install hub

      - name: Fetch Wheel
        uses: actions/download-artifact@v3
        with:
          name: Wheel
          path: dist

      - name: Fetch RPMs
        uses: actions/download-artifact@v3
        with:
          name: RPMs
          path: dist

      - name: Upload python dist content
        run: |
          gh release upload ${{ github.ref_name }} \
            dist/*.whl \
            dist/*.src.rpm \
            dist/*/RPMS/noarch/*.rpm
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

  pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    needs:
      - build-wheel

    environment:
      name: pypi
      url: https://pypi.org/p/kojismokydingo

    permissions:
      id-token: write

    steps:
      - name: Fetch python dist content
        uses: actions/download-artifact@v3
        with:
          name: Wheel
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  announce:
    name: Announce release
    runs-on: ubuntu-latest

    needs:
      - attach-assets
      - pypi

    steps:
      - name: Fetch python dist content
        uses: actions/download-artifact@v3
        with:
          name: Wheel
          path: dist

      - name: Get the package version
        run: |
          echo "DIST_VERSION=$(cat dist/VERSION)" >> "$GITHUB_ENV"

      - name: Get current date
        run: |
          echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: "\
        Trigger announcement for ${{ env.DIST_VERSION }}(tag
        ${{ github.ref_name }}) on ${{ env.RELEASE_DATE }}"
        uses: ./.github/workflows/announce.yml
        with:
          version: ${{ env.DIST_VERSION }}
          date: ${{ env.RELEASE_DATE }}
          ref: ${{ github.ref_name }}


# The end.
