
name: RPM Build


on:
  workflow_call:
  workflow_dispatch:


jobs:
  build-srpm:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Determine version
        id: version
        run: |
          echo "ksd_version=$(python -B setup.py --version)" >> "$GITHUB_ENV"

      - name: Install system dependencies
        run: |
          sudo apt-get install bash git make

      - name: Generate archive
        run: |
          make archive

      - name: Generate Source RPM
        id: srpm
        uses: next-actions/build-srpm@master
        with:
          tarball: kojismokydingo-${{ env.ksd_version }}.tar.gz
          specfile: kojismokydingo.spec

      - name: Move Source RPM to dist
        run: |
          mkdir -p dist
          mv -v ${{ steps.srpm.outputs.path }} dist/

      - name: Store Source RPM
        uses: actions/upload-artifact@v3
        with:
          name: RPMs
          path: dist/*.src.rpm


  build-platform-rpm:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          # - 'fedora30'
          # - 'fedora32'
          # - 'fedora34'
          - 'fedora36'
          - 'fedora37'
          - 'fedora38'
          - 'rockylinux8'
          - 'rockylinux9'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get install bash git make podman

      - name: Generate archive
        run: |
          make archive

      - name: Generate ${{ matrix.platform }} RPM
        run: |
          tools/launch-build.sh ${{ matrix.platform }}

      - name: Store ${{ matrix.platform }} RPM
        uses: actions/upload-artifact@v3
        with:
          name: RPMs
          path: dist/${{ matrix.platform }}/RPMS/noarch/*.rpm


# The end.
