# Github Action definition for running tox across the supported python
# versions. Intended to be triggered on push to master and on filing
# of a pull_request, when those pushes hit something that impacts the
# running of the tests.


name: Tox


on:
  push:
    branches:
      - master
    ignore-paths:
      - 'docs/**'
      - 'examples/**'
      - 'tools/**'
    paths:
      - 'setup.cfg'
      - '**/*.py'
      - '**/*.pyi'

  pull_request:
    ignore-paths:
      - 'docs/**'
      - 'examples/**'
      - 'tools/**'
    paths:
      - 'setup.cfg'
      - '**/*.py'
      - '**/*.pyi'


jobs:
  pre-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get install libkrb5-dev

      - name: Install python dependencies
        run: |
          pip install tox tox-gh-actions wheel

      - name: Run Flake8
        run: tox -e flake8

      - name: Run MyPy
        run: tox -e mypy

      - name: Run Bandit
        run: tox -e bandit

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    needs:
      - pre-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get install libkrb5-dev

      - name: Install python dependencies
        run: |
          pip install tox tox-gh-actions wheel

      - name: Running tox
        run: tox

      - name: Collect coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: '.coverage.py*'

  coverage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    needs:
      - tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch coverage results
        uses: actions/download-artifact@v3
        with:
          name: coverage-data

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get install libkrb5-dev

      - name: Install python dependencies
        run: |
          pip install tox tox-gh-actions

      - name: Coverage report
        run: |
          tox -e coverage

      - name: Upload to coveralls
        uses: coverallsapp/github-action@v2


# The end.
